# Form implementation generated from reading ui file 'add_itemn.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_add_item_dialog(object):
    def setupUi(self, add_item_dialog):
        add_item_dialog.setObjectName("add_item_dialog")
        add_item_dialog.resize(400, 300)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(20)
        add_item_dialog.setFont(font)
        self.label = QtWidgets.QLabel(add_item_dialog)
        self.label.setGeometry(QtCore.QRect(110, 10, 151, 31))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(add_item_dialog)
        QtCore.QMetaObject.connectSlotsByName(add_item_dialog)

    def retranslateUi(self, add_item_dialog):
        _translate = QtCore.QCoreApplication.translate
        add_item_dialog.setWindowTitle(_translate("add_item_dialog", "Dialog"))
        self.label.setText(_translate("add_item_dialog", "Add Item"))
