# Form implementation generated from reading ui file 'assign_word.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_assign_word_dialog(object):
    def setupUi(self, assign_word_dialog):
        assign_word_dialog.setObjectName("assign_word_dialog")
        assign_word_dialog.resize(590, 538)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(20)
        assign_word_dialog.setFont(font)

        self.retranslateUi(assign_word_dialog)
        QtCore.QMetaObject.connectSlotsByName(assign_word_dialog)

    def retranslateUi(self, assign_word_dialog):
        _translate = QtCore.QCoreApplication.translate
        assign_word_dialog.setWindowTitle(_translate("assign_word_dialog", "Assign Word"))
