# Form implementation generated from reading ui file 'clock_out_successful.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ClockOutSuccessful(object):
    def setupUi(self, ClockOutSuccessful):
        ClockOutSuccessful.setObjectName("ClockOutSuccessful")
        ClockOutSuccessful.resize(402, 68)
        self.label = QtWidgets.QLabel(ClockOutSuccessful)
        self.label.setGeometry(QtCore.QRect(0, 10, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(ClockOutSuccessful)
        QtCore.QMetaObject.connectSlotsByName(ClockOutSuccessful)

    def retranslateUi(self, ClockOutSuccessful):
        _translate = QtCore.QCoreApplication.translate
        ClockOutSuccessful.setWindowTitle(_translate("ClockOutSuccessful", "Logout Successful"))
        self.label.setText(_translate("ClockOutSuccessful", "Clock Out Successful"))
