# Form implementation generated from reading ui file 'clock_in_successful.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ClockInSuccessful(object):
    def setupUi(self, ClockInSuccessful):
        ClockInSuccessful.setObjectName("ClockInSuccessful")
        ClockInSuccessful.resize(400, 67)
        self.label = QtWidgets.QLabel(ClockInSuccessful)
        self.label.setGeometry(QtCore.QRect(10, 10, 361, 51))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(ClockInSuccessful)
        QtCore.QMetaObject.connectSlotsByName(ClockInSuccessful)

    def retranslateUi(self, ClockInSuccessful):
        _translate = QtCore.QCoreApplication.translate
        ClockInSuccessful.setWindowTitle(_translate("ClockInSuccessful", "Login Successful"))
        self.label.setText(_translate("ClockInSuccessful", "Clock In Successful"))
