# Form implementation generated from reading ui file 'discount_selection.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_discount_check_dialog(object):
    def setupUi(self, discount_check_dialog):
        discount_check_dialog.setObjectName("discount_check_dialog")
        discount_check_dialog.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(discount_check_dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 381, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_percent = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_percent.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(16)
        self.btn_percent.setFont(font)
        self.btn_percent.setObjectName("btn_percent")
        self.verticalLayout.addWidget(self.btn_percent)
        self.btn_amount = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_amount.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(16)
        self.btn_amount.setFont(font)
        self.btn_amount.setObjectName("btn_amount")
        self.verticalLayout.addWidget(self.btn_amount)

        self.retranslateUi(discount_check_dialog)
        QtCore.QMetaObject.connectSlotsByName(discount_check_dialog)

    def retranslateUi(self, discount_check_dialog):
        _translate = QtCore.QCoreApplication.translate
        discount_check_dialog.setWindowTitle(_translate("discount_check_dialog", "Discount Type"))
        self.btn_percent.setText(_translate("discount_check_dialog", "Percent"))
        self.btn_amount.setText(_translate("discount_check_dialog", "Fixed Amount"))
