# Form implementation generated from reading ui file 'employee_check.ui'
#
# Created by: PyQt6 UI code generator 6.0.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_payroll_check_display(object):
    def setupUi(self, payroll_check_display):
        payroll_check_display.setObjectName("payroll_check_display")
        payroll_check_display.resize(1167, 610)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(20)
        payroll_check_display.setFont(font)
        self.label = QtWidgets.QLabel(payroll_check_display)
        self.label.setGeometry(QtCore.QRect(10, 10, 681, 41))
        self.label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.label.setObjectName("label")
        self.lbl_chk_no = QtWidgets.QLabel(payroll_check_display)
        self.lbl_chk_no.setGeometry(QtCore.QRect(10, 60, 611, 31))
        self.lbl_chk_no.setObjectName("lbl_chk_no")
        self.lbl_date = QtWidgets.QLabel(payroll_check_display)
        self.lbl_date.setGeometry(QtCore.QRect(10, 120, 611, 31))
        self.lbl_date.setObjectName("lbl_date")
        self.tableWidget = QtWidgets.QTableWidget(payroll_check_display)
        self.tableWidget.setGeometry(QtCore.QRect(770, 40, 381, 91))
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget_2 = QtWidgets.QTableWidget(payroll_check_display)
        self.tableWidget_2.setGeometry(QtCore.QRect(770, 140, 381, 341))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_2.setSizePolicy(sizePolicy)
        self.tableWidget_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.lbl_name = QtWidgets.QLabel(payroll_check_display)
        self.lbl_name.setGeometry(QtCore.QRect(770, 10, 371, 21))
        self.lbl_name.setObjectName("lbl_name")
        self.lbl_pay_to = QtWidgets.QLabel(payroll_check_display)
        self.lbl_pay_to.setGeometry(QtCore.QRect(10, 180, 451, 41))
        self.lbl_pay_to.setObjectName("lbl_pay_to")
        self.lbl_numeric_amt = QtWidgets.QLabel(payroll_check_display)
        self.lbl_numeric_amt.setGeometry(QtCore.QRect(470, 180, 141, 31))
        self.lbl_numeric_amt.setAlignment(QtCore.Qt.Alignment.AlignRight|QtCore.Qt.Alignment.AlignTrailing|QtCore.Qt.Alignment.AlignVCenter)
        self.lbl_numeric_amt.setObjectName("lbl_numeric_amt")
        self.lbl_written_amt = QtWidgets.QLabel(payroll_check_display)
        self.lbl_written_amt.setGeometry(QtCore.QRect(10, 280, 741, 51))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        self.lbl_written_amt.setFont(font)
        self.lbl_written_amt.setObjectName("lbl_written_amt")
        self.lbl_payer = QtWidgets.QLabel(payroll_check_display)
        self.lbl_payer.setGeometry(QtCore.QRect(10, 420, 621, 51))
        self.lbl_payer.setObjectName("lbl_payer")
        self.btn_ok = QtWidgets.QPushButton(payroll_check_display)
        self.btn_ok.setGeometry(QtCore.QRect(310, 530, 251, 61))
        self.btn_ok.setObjectName("btn_ok")

        self.retranslateUi(payroll_check_display)
        QtCore.QMetaObject.connectSlotsByName(payroll_check_display)

    def retranslateUi(self, payroll_check_display):
        _translate = QtCore.QCoreApplication.translate
        payroll_check_display.setWindowTitle(_translate("payroll_check_display", "Employee Check"))
        self.label.setText(_translate("payroll_check_display", "Larry\'s Sartorial Shoppe Employee Check"))
        self.lbl_chk_no.setText(_translate("payroll_check_display", "Check Number:"))
        self.lbl_date.setText(_translate("payroll_check_display", "Date:"))
        self.lbl_name.setText(_translate("payroll_check_display", "Name:"))
        self.lbl_pay_to.setText(_translate("payroll_check_display", "Pay to the order of:"))
        self.lbl_numeric_amt.setText(_translate("payroll_check_display", "$"))
        self.lbl_written_amt.setText(_translate("payroll_check_display", "Amount:"))
        self.lbl_payer.setText(_translate("payroll_check_display", "Payer Name: __________________________"))
        self.btn_ok.setText(_translate("payroll_check_display", "OK"))
