# Form implementation generated from reading ui file 'employee_setup.ui'
#
# Created by: PyQt6 UI code generator 6.0.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_employee_setup(object):
    def setupUi(self, employee_setup):
        employee_setup.setObjectName("employee_setup")
        employee_setup.resize(756, 733)
        self.verticalLayoutWidget = QtWidgets.QWidget(employee_setup)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 109, 231, 551))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tbl_employees = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tbl_employees.setColumnCount(2)
        self.tbl_employees.setObjectName("tbl_employees")
        self.tbl_employees.setRowCount(0)
        self.verticalLayout.addWidget(self.tbl_employees)
        self.label = QtWidgets.QLabel(employee_setup)
        self.label.setGeometry(QtCore.QRect(10, 10, 741, 31))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.label.setObjectName("label")
        self.lbl_fname = QtWidgets.QLabel(employee_setup)
        self.lbl_fname.setGeometry(QtCore.QRect(270, 110, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_fname.setFont(font)
        self.lbl_fname.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.lbl_fname.setObjectName("lbl_fname")
        self.txt_fname = QtWidgets.QLineEdit(employee_setup)
        self.txt_fname.setGeometry(QtCore.QRect(430, 110, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        self.txt_fname.setFont(font)
        self.txt_fname.setObjectName("txt_fname")

        self.retranslateUi(employee_setup)
        QtCore.QMetaObject.connectSlotsByName(employee_setup)

    def retranslateUi(self, employee_setup):
        _translate = QtCore.QCoreApplication.translate
        employee_setup.setWindowTitle(_translate("employee_setup", "Dialog"))
        self.label.setText(_translate("employee_setup", "Employee Setup"))
        self.lbl_fname.setText(_translate("employee_setup", "First Name"))
