# Form implementation generated from reading ui file 'manage_account.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_manage_account_dialog(object):
    def setupUi(self, manage_account_dialog):
        manage_account_dialog.setObjectName("manage_account_dialog")
        manage_account_dialog.resize(400, 300)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(20)
        manage_account_dialog.setFont(font)
        self.label = QtWidgets.QLabel(manage_account_dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 381, 41))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(manage_account_dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 119, 381, 102))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.btn_cancel.sizePolicy().hasHeightForWidth())
        self.btn_cancel.setSizePolicy(sizePolicy)
        self.btn_cancel.setMinimumSize(QtCore.QSize(100, 100))
        self.btn_cancel.setMaximumSize(QtCore.QSize(100, 100))
        self.btn_cancel.setBaseSize(QtCore.QSize(12, 2))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(22)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.btn_payment = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.btn_payment.sizePolicy().hasHeightForWidth())
        self.btn_payment.setSizePolicy(sizePolicy)
        self.btn_payment.setMinimumSize(QtCore.QSize(100, 100))
        self.btn_payment.setMaximumSize(QtCore.QSize(100, 100))
        self.btn_payment.setBaseSize(QtCore.QSize(12, 2))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.btn_payment.setFont(font)
        self.btn_payment.setObjectName("btn_payment")
        self.horizontalLayout.addWidget(self.btn_payment)

        self.retranslateUi(manage_account_dialog)
        QtCore.QMetaObject.connectSlotsByName(manage_account_dialog)

    def retranslateUi(self, manage_account_dialog):
        _translate = QtCore.QCoreApplication.translate
        manage_account_dialog.setWindowTitle(_translate("manage_account_dialog", "Manage Account"))
        self.label.setText(_translate("manage_account_dialog", "Manage Account"))
        self.btn_cancel.setText(_translate("manage_account_dialog", "Cancel"))
        self.btn_payment.setText(_translate("manage_account_dialog", "Make\n"
"Payment"))
