# Form implementation generated from reading ui file 'open_orders.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_open_orders_dialog(object):
    def setupUi(self, open_orders_dialog):
        open_orders_dialog.setObjectName("open_orders_dialog")
        open_orders_dialog.resize(400, 355)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(20)
        open_orders_dialog.setFont(font)
        self.label = QtWidgets.QLabel(open_orders_dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 381, 31))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(open_orders_dialog)
        self.tableWidget.setGeometry(QtCore.QRect(15, 50, 371, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayoutWidget = QtWidgets.QWidget(open_orders_dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 250, 381, 102))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_ok = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.btn_ok.sizePolicy().hasHeightForWidth())
        self.btn_ok.setSizePolicy(sizePolicy)
        self.btn_ok.setMinimumSize(QtCore.QSize(100, 100))
        self.btn_ok.setMaximumSize(QtCore.QSize(100, 100))
        self.btn_ok.setBaseSize(QtCore.QSize(12, 2))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(22)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.btn_ok.setFont(font)
        self.btn_ok.setObjectName("btn_ok")
        self.horizontalLayout.addWidget(self.btn_ok)

        self.retranslateUi(open_orders_dialog)
        QtCore.QMetaObject.connectSlotsByName(open_orders_dialog)

    def retranslateUi(self, open_orders_dialog):
        _translate = QtCore.QCoreApplication.translate
        open_orders_dialog.setWindowTitle(_translate("open_orders_dialog", "Open Orders"))
        self.label.setText(_translate("open_orders_dialog", "Open Orders"))
        self.btn_ok.setText(_translate("open_orders_dialog", "OK"))
