# Form implementation generated from reading ui file 'payroll.ui'
#
# Created by: PyQt6 UI code generator 6.0.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_payroll_dialog(object):
    def setupUi(self, payroll_dialog):
        payroll_dialog.setObjectName("payroll_dialog")
        payroll_dialog.resize(461, 393)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(20)
        payroll_dialog.setFont(font)
        self.label = QtWidgets.QLabel(payroll_dialog)
        self.label.setGeometry(QtCore.QRect(130, 10, 161, 31))
        self.label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.label.setObjectName("label")
        self.tableView = QtWidgets.QTableView(payroll_dialog)
        self.tableView.setGeometry(QtCore.QRect(10, 60, 431, 192))
        self.tableView.setObjectName("tableView")
        self.horizontalLayoutWidget = QtWidgets.QWidget(payroll_dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 260, 431, 102))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_cut_check = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.btn_cut_check.sizePolicy().hasHeightForWidth())
        self.btn_cut_check.setSizePolicy(sizePolicy)
        self.btn_cut_check.setMinimumSize(QtCore.QSize(100, 100))
        self.btn_cut_check.setMaximumSize(QtCore.QSize(100, 100))
        self.btn_cut_check.setBaseSize(QtCore.QSize(12, 2))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(22)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.btn_cut_check.setFont(font)
        self.btn_cut_check.setObjectName("btn_cut_check")
        self.horizontalLayout.addWidget(self.btn_cut_check)
        self.btn_edit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.btn_edit.sizePolicy().hasHeightForWidth())
        self.btn_edit.setSizePolicy(sizePolicy)
        self.btn_edit.setMinimumSize(QtCore.QSize(100, 100))
        self.btn_edit.setMaximumSize(QtCore.QSize(100, 100))
        self.btn_edit.setBaseSize(QtCore.QSize(12, 2))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(22)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.btn_edit.setFont(font)
        self.btn_edit.setObjectName("btn_edit")
        self.horizontalLayout.addWidget(self.btn_edit)
        self.btn_cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.btn_cancel.sizePolicy().hasHeightForWidth())
        self.btn_cancel.setSizePolicy(sizePolicy)
        self.btn_cancel.setMinimumSize(QtCore.QSize(100, 100))
        self.btn_cancel.setMaximumSize(QtCore.QSize(100, 100))
        self.btn_cancel.setBaseSize(QtCore.QSize(12, 2))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(22)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)

        self.retranslateUi(payroll_dialog)
        QtCore.QMetaObject.connectSlotsByName(payroll_dialog)

    def retranslateUi(self, payroll_dialog):
        _translate = QtCore.QCoreApplication.translate
        payroll_dialog.setWindowTitle(_translate("payroll_dialog", "Payroll"))
        self.label.setText(_translate("payroll_dialog", "Payroll"))
        self.btn_cut_check.setText(_translate("payroll_dialog", "Cut\n"
"Check"))
        self.btn_edit.setText(_translate("payroll_dialog", "Edit"))
        self.btn_cancel.setText(_translate("payroll_dialog", "Cancel"))
