# Form implementation generated from reading ui file 'select_employee.ui'
#
# Created by: PyQt6 UI code generator 6.0.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_time_clock_dialog(object):
    def setupUi(self, time_clock_dialog):
        time_clock_dialog.setObjectName("time_clock_dialog")
        time_clock_dialog.resize(762, 629)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(20)
        time_clock_dialog.setFont(font)
        self.label = QtWidgets.QLabel(time_clock_dialog)
        self.label.setGeometry(QtCore.QRect(250, 10, 231, 101))
        self.label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(time_clock_dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 89, 741, 441))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.retranslateUi(time_clock_dialog)
        QtCore.QMetaObject.connectSlotsByName(time_clock_dialog)

    def retranslateUi(self, time_clock_dialog):
        _translate = QtCore.QCoreApplication.translate
        time_clock_dialog.setWindowTitle(_translate("time_clock_dialog", "Select Employee"))
        self.label.setText(_translate("time_clock_dialog", "Select Employee"))
