# Form implementation generated from reading ui file 'select_employee.ui'
#
# Created by: PyQt6 UI code generator 6.0.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_time_clock_dialog(object):
    def setupUi(self, time_clock_dialog):
        time_clock_dialog.setObjectName("time_clock_dialog")
        time_clock_dialog.resize(762, 629)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(20)
        time_clock_dialog.setFont(font)
        self.label = QtWidgets.QLabel(time_clock_dialog)
        self.label.setGeometry(QtCore.QRect(250, 10, 231, 101))
        self.label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(time_clock_dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 89, 741, 441))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_emp_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_emp_5.setObjectName("btn_emp_5")
        self.gridLayout.addWidget(self.btn_emp_5, 4, 0, 1, 1)
        self.btn_emp_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_emp_8.setObjectName("btn_emp_8")
        self.gridLayout.addWidget(self.btn_emp_8, 2, 1, 1, 1)
        self.btn_emp_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_emp_3.setObjectName("btn_emp_3")
        self.gridLayout.addWidget(self.btn_emp_3, 2, 0, 1, 1)
        self.btn_emp_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_emp_4.setObjectName("btn_emp_4")
        self.gridLayout.addWidget(self.btn_emp_4, 3, 0, 1, 1)
        self.btn_emp_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_emp_6.setObjectName("btn_emp_6")
        self.gridLayout.addWidget(self.btn_emp_6, 0, 1, 1, 1)
        self.btn_emp_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_emp_9.setObjectName("btn_emp_9")
        self.gridLayout.addWidget(self.btn_emp_9, 3, 1, 1, 1)
        self.btn_emp_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_emp_2.setObjectName("btn_emp_2")
        self.gridLayout.addWidget(self.btn_emp_2, 1, 0, 1, 1)
        self.btn_emp_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_emp_7.setObjectName("btn_emp_7")
        self.gridLayout.addWidget(self.btn_emp_7, 1, 1, 1, 1)
        self.btn_emp_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_emp_1.setObjectName("btn_emp_1")
        self.gridLayout.addWidget(self.btn_emp_1, 0, 0, 1, 1)
        self.btn_emp_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_emp_10.setObjectName("btn_emp_10")
        self.gridLayout.addWidget(self.btn_emp_10, 4, 1, 1, 1)
        self.btn_emp_11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_emp_11.setObjectName("btn_emp_11")
        self.gridLayout.addWidget(self.btn_emp_11, 0, 2, 1, 1)

        self.retranslateUi(time_clock_dialog)
        QtCore.QMetaObject.connectSlotsByName(time_clock_dialog)

    def retranslateUi(self, time_clock_dialog):
        _translate = QtCore.QCoreApplication.translate
        time_clock_dialog.setWindowTitle(_translate("time_clock_dialog", "Select Employee"))
        self.label.setText(_translate("time_clock_dialog", "Select Employee"))
        self.btn_emp_5.setText(_translate("time_clock_dialog", "Timothy"))
        self.btn_emp_8.setText(_translate("time_clock_dialog", "Jeremy"))
        self.btn_emp_3.setText(_translate("time_clock_dialog", "Renae"))
        self.btn_emp_4.setText(_translate("time_clock_dialog", "Rachel"))
        self.btn_emp_6.setText(_translate("time_clock_dialog", "Jennifer"))
        self.btn_emp_9.setText(_translate("time_clock_dialog", "Linda"))
        self.btn_emp_2.setText(_translate("time_clock_dialog", "John"))
        self.btn_emp_7.setText(_translate("time_clock_dialog", "Dylan"))
        self.btn_emp_1.setText(_translate("time_clock_dialog", "Larry"))
        self.btn_emp_10.setText(_translate("time_clock_dialog", "Mary"))
        self.btn_emp_11.setText(_translate("time_clock_dialog", "Derrick"))
