# Form implementation generated from reading ui file 'stock.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_stock_dialog(object):
    def setupUi(self, stock_dialog):
        stock_dialog.setObjectName("stock_dialog")
        stock_dialog.resize(367, 492)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(20)
        stock_dialog.setFont(font)
        self.label = QtWidgets.QLabel(stock_dialog)
        self.label.setGeometry(QtCore.QRect(70, 0, 181, 51))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(stock_dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 49, 353, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_vendor_functs = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_vendor_functs.setObjectName("btn_vendor_functs")
        self.verticalLayout.addWidget(self.btn_vendor_functs)
        self.btn_perform_count = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_perform_count.setObjectName("btn_perform_count")
        self.verticalLayout.addWidget(self.btn_perform_count)
        self.btn_receive_order = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_receive_order.setObjectName("btn_receive_order")
        self.verticalLayout.addWidget(self.btn_receive_order)
        self.btn_cancel = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_cancel.setObjectName("btn_cancel")
        self.verticalLayout.addWidget(self.btn_cancel)

        self.retranslateUi(stock_dialog)
        QtCore.QMetaObject.connectSlotsByName(stock_dialog)

    def retranslateUi(self, stock_dialog):
        _translate = QtCore.QCoreApplication.translate
        stock_dialog.setWindowTitle(_translate("stock_dialog", "Stock"))
        self.label.setText(_translate("stock_dialog", "Stock"))
        self.btn_vendor_functs.setText(_translate("stock_dialog", "Vendor Functions"))
        self.btn_perform_count.setText(_translate("stock_dialog", "Perform Count"))
        self.btn_receive_order.setText(_translate("stock_dialog", "Receive Order"))
        self.btn_cancel.setText(_translate("stock_dialog", "Cancel"))
