# Form implementation generated from reading ui file 'timecard.ui'
#
# Created by: PyQt6 UI code generator 6.0.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_timecard_dialog(object):
    def setupUi(self, timecard_dialog):
        timecard_dialog.setObjectName("timecard_dialog")
        timecard_dialog.resize(623, 603)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(20)
        timecard_dialog.setFont(font)
        self.lbl_name = QtWidgets.QLabel(timecard_dialog)
        self.lbl_name.setGeometry(QtCore.QRect(30, 10, 311, 31))
        self.lbl_name.setObjectName("lbl_name")
        self.line = QtWidgets.QFrame(timecard_dialog)
        self.line.setGeometry(QtCore.QRect(360, 10, 20, 41))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.lbl_id = QtWidgets.QLabel(timecard_dialog)
        self.lbl_id.setGeometry(QtCore.QRect(380, 10, 221, 31))
        self.lbl_id.setObjectName("lbl_id")
        self.tableWidget = QtWidgets.QTableWidget(timecard_dialog)
        self.tableWidget.setGeometry(QtCore.QRect(20, 60, 591, 411))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.lbl_total_hours = QtWidgets.QLabel(timecard_dialog)
        self.lbl_total_hours.setGeometry(QtCore.QRect(260, 480, 351, 41))
        self.lbl_total_hours.setAlignment(QtCore.Qt.Alignment.AlignRight|QtCore.Qt.Alignment.AlignTrailing|QtCore.Qt.Alignment.AlignVCenter)
        self.lbl_total_hours.setObjectName("lbl_total_hours")
        self.btn_ok = QtWidgets.QPushButton(timecard_dialog)
        self.btn_ok.setGeometry(QtCore.QRect(200, 530, 201, 51))
        self.btn_ok.setObjectName("btn_ok")

        self.retranslateUi(timecard_dialog)
        QtCore.QMetaObject.connectSlotsByName(timecard_dialog)

    def retranslateUi(self, timecard_dialog):
        _translate = QtCore.QCoreApplication.translate
        timecard_dialog.setWindowTitle(_translate("timecard_dialog", "Timecard"))
        self.lbl_name.setText(_translate("timecard_dialog", "Name:"))
        self.lbl_id.setText(_translate("timecard_dialog", "ID:"))
        self.lbl_total_hours.setText(_translate("timecard_dialog", "Total Hours: "))
        self.btn_ok.setText(_translate("timecard_dialog", "OK"))
