# Form implementation generated from reading ui file 'vendor_order.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_new_vendor_order_dialog(object):
    def setupUi(self, new_vendor_order_dialog):
        new_vendor_order_dialog.setObjectName("new_vendor_order_dialog")
        new_vendor_order_dialog.resize(400, 300)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(20)
        new_vendor_order_dialog.setFont(font)
        self.label = QtWidgets.QLabel(new_vendor_order_dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 391, 41))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.tableView = QtWidgets.QTableView(new_vendor_order_dialog)
        self.tableView.setGeometry(QtCore.QRect(10, 40, 381, 131))
        self.tableView.setObjectName("tableView")
        self.horizontalLayoutWidget = QtWidgets.QWidget(new_vendor_order_dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 180, 381, 102))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_edit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.btn_edit.sizePolicy().hasHeightForWidth())
        self.btn_edit.setSizePolicy(sizePolicy)
        self.btn_edit.setMinimumSize(QtCore.QSize(100, 100))
        self.btn_edit.setMaximumSize(QtCore.QSize(100, 100))
        self.btn_edit.setBaseSize(QtCore.QSize(12, 2))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(20)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.btn_edit.setFont(font)
        self.btn_edit.setObjectName("btn_edit")
        self.horizontalLayout.addWidget(self.btn_edit)
        self.btn_cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.btn_cancel.sizePolicy().hasHeightForWidth())
        self.btn_cancel.setSizePolicy(sizePolicy)
        self.btn_cancel.setMinimumSize(QtCore.QSize(100, 100))
        self.btn_cancel.setMaximumSize(QtCore.QSize(100, 100))
        self.btn_cancel.setBaseSize(QtCore.QSize(12, 2))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(22)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)

        self.retranslateUi(new_vendor_order_dialog)
        QtCore.QMetaObject.connectSlotsByName(new_vendor_order_dialog)

    def retranslateUi(self, new_vendor_order_dialog):
        _translate = QtCore.QCoreApplication.translate
        new_vendor_order_dialog.setWindowTitle(_translate("new_vendor_order_dialog", "Vendor Order"))
        self.label.setText(_translate("new_vendor_order_dialog", "Vendor Order"))
        self.btn_edit.setText(_translate("new_vendor_order_dialog", "Edit"))
        self.btn_cancel.setText(_translate("new_vendor_order_dialog", "Cancel"))
